// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/jflex/lexer.flex

/**
 *  This code is part of the lab exercises for the Compilers course
 *  at Harokopio University of Athens, Dept. of Informatics and Telematics.
 */

import static java.lang.System.out;
import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public final class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SINGLE_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\3\u1f00"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u1f00\1\u4a00\1\u1f00\1\u4b00\1\u4c00\2\u1f00\3\u0100"+
    "\1\u4d00\1\u4e00\1\u4f00\12\u1f00\4\u0100\1\u5000\17\u1f00\2\u0100"+
    "\1\u5100\41\u1f00\2\u0100\1\u5200\1\u5300\3\u1f00\1\u5400\27\u0100"+
    "\1\u5500\2\u0100\1\u5600\45\u1f00\1\u0100\1\u5700\1\u5800\11\u1f00"+
    "\1\u5900\24\u1f00\1\u5a00\1\u5b00\1\u1f00\1\u5c00\1\u5d00\1\u5e00"+
    "\1\u5f00\2\u1f00\1\u6000\5\u1f00\1\u6100\7\u1f00\1\u6200\1\u6300"+
    "\4\u1f00\1\u6400\21\u1f00\246\u0100\1\u6500\20\u0100\1\u6600\1\u6700"+
    "\25\u0100\1\u6800\34\u0100\1\u6900\14\u1f00\2\u0100\1\u6a00\u0b05\u1f00"+
    "\1\u6b00\1\u6c00\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\6"+
    "\1\1\1\6\1\7\1\10\1\11\2\6\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\2\6\1\21\11\22"+
    "\1\23\1\24\1\25\1\26\1\27\2\6\32\30\1\31"+
    "\1\32\1\33\1\6\1\30\1\6\1\34\1\30\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\2\30\1\44"+
    "\1\45\1\46\1\47\2\30\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\3\30\1\56\1\6\1\57\1\6\6\0"+
    "\1\60\32\0\2\6\4\30\4\6\1\30\2\6\1\0"+
    "\7\6\1\30\4\6\1\30\5\6\27\30\1\6\37\30"+
    "\1\6\u01ca\30\4\6\14\30\16\6\5\30\7\6\1\30"+
    "\1\6\1\30\21\6\160\0\5\30\1\6\2\30\2\6"+
    "\4\30\1\6\1\30\6\6\1\30\1\6\3\30\1\6"+
    "\1\30\1\6\24\30\1\6\123\30\1\6\213\30\1\6"+
    "\5\0\2\6\246\30\1\6\46\30\2\6\1\30\7\6"+
    "\47\30\7\6\1\30\1\6\55\0\1\6\1\0\1\6"+
    "\2\0\1\6\2\0\1\6\1\0\10\6\33\30\5\6"+
    "\3\30\15\6\6\0\5\6\1\30\4\6\13\0\1\6"+
    "\1\0\3\6\53\30\37\0\4\6\2\30\1\0\143\30"+
    "\1\6\1\30\10\0\1\6\6\0\2\30\2\0\1\6"+
    "\4\0\2\30\12\0\3\30\2\6\1\30\17\6\1\0"+
    "\1\30\1\0\36\30\33\0\2\6\131\30\13\0\1\30"+
    "\16\6\12\0\41\30\11\0\2\30\4\6\1\30\5\6"+
    "\26\30\4\0\1\30\11\0\1\30\3\0\1\30\5\0"+
    "\22\6\31\30\3\0\4\6\13\30\65\6\25\30\1\6"+
    "\10\30\26\6\60\0\66\30\3\0\1\30\22\0\1\30"+
    "\7\0\12\30\2\0\2\6\12\0\1\6\20\30\3\0"+
    "\1\6\10\30\2\6\2\30\2\6\26\30\1\6\7\30"+
    "\1\6\1\30\3\6\4\30\2\6\1\0\1\30\7\0"+
    "\2\6\2\0\2\6\3\0\1\30\10\6\1\0\4\6"+
    "\2\30\1\6\3\30\2\0\2\6\12\0\4\30\7\6"+
    "\2\30\4\6\3\0\1\6\6\30\4\6\2\30\2\6"+
    "\26\30\1\6\7\30\1\6\2\30\1\6\2\30\1\6"+
    "\2\30\2\6\1\0\1\6\5\0\4\6\2\0\2\6"+
    "\3\0\3\6\1\0\7\6\4\30\1\6\1\30\7\6"+
    "\14\0\3\30\1\0\13\6\3\0\1\6\11\30\1\6"+
    "\3\30\1\6\26\30\1\6\7\30\1\6\2\30\1\6"+
    "\5\30\2\6\1\0\1\30\10\0\1\6\3\0\1\6"+
    "\3\0\2\6\1\30\17\6\2\30\2\0\2\6\12\0"+
    "\1\6\1\30\7\6\1\30\6\0\1\6\3\0\1\6"+
    "\10\30\2\6\2\30\2\6\26\30\1\6\7\30\1\6"+
    "\2\30\1\6\5\30\2\6\1\0\1\30\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\2\0\4\6\2\30\1\6"+
    "\3\30\2\0\2\6\12\0\1\6\1\30\20\6\1\0"+
    "\1\30\1\6\6\30\3\6\3\30\1\6\4\30\3\6"+
    "\2\30\1\6\1\30\1\6\2\30\3\6\2\30\3\6"+
    "\3\30\3\6\14\30\4\6\5\0\3\6\3\0\1\6"+
    "\4\0\2\6\1\30\6\6\1\0\16\6\12\0\11\6"+
    "\1\30\6\6\4\0\1\6\10\30\1\6\3\30\1\6"+
    "\27\30\1\6\20\30\3\6\1\30\7\0\1\6\3\0"+
    "\1\6\4\0\7\6\2\0\1\6\3\30\5\6\2\30"+
    "\2\0\2\6\12\0\20\6\1\30\3\0\1\6\10\30"+
    "\1\6\3\30\1\6\27\30\1\6\12\30\1\6\5\30"+
    "\2\6\1\0\1\30\7\0\1\6\3\0\1\6\4\0"+
    "\7\6\2\0\7\6\1\30\1\6\2\30\2\0\2\6"+
    "\12\0\1\6\2\30\15\6\4\0\1\6\10\30\1\6"+
    "\3\30\1\6\51\30\2\0\1\30\7\0\1\6\3\0"+
    "\1\6\4\0\1\30\5\6\3\30\1\0\7\6\3\30"+
    "\2\0\2\6\12\0\12\6\6\30\2\6\2\0\1\6"+
    "\22\30\3\6\30\30\1\6\11\30\1\6\1\30\2\6"+
    "\7\30\3\6\1\0\4\6\6\0\1\6\1\0\1\6"+
    "\10\0\6\6\12\0\2\6\2\0\15\6\60\30\1\0"+
    "\2\30\7\0\4\6\10\30\10\0\1\6\12\0\47\6"+
    "\2\30\1\6\1\30\2\6\2\30\1\6\1\30\2\6"+
    "\1\30\6\6\4\30\1\6\7\30\1\6\3\30\1\6"+
    "\1\30\1\6\1\30\2\6\2\30\1\6\4\30\1\0"+
    "\2\30\6\0\1\6\2\0\1\30\2\6\5\30\1\6"+
    "\1\30\1\6\6\0\2\6\12\0\2\6\4\30\40\6"+
    "\1\30\27\6\2\0\6\6\12\0\13\6\1\0\1\6"+
    "\1\0\1\6\1\0\4\6\2\0\10\30\1\6\44\30"+
    "\4\6\24\0\1\6\2\0\5\30\13\0\1\6\44\0"+
    "\11\6\1\0\71\6\53\30\24\0\1\30\12\0\6\6"+
    "\6\30\4\0\4\30\3\0\1\30\3\0\2\30\7\0"+
    "\3\30\4\0\15\30\14\0\1\30\17\0\2\6\46\30"+
    "\1\6\1\30\5\6\1\30\2\6\53\30\1\6\115\30"+
    "\1\6\4\30\2\6\7\30\1\6\1\30\1\6\4\30"+
    "\2\6\51\30\1\6\4\30\2\6\41\30\1\6\4\30"+
    "\2\6\7\30\1\6\1\30\1\6\4\30\2\6\17\30"+
    "\1\6\71\30\1\6\4\30\2\6\103\30\2\6\3\0"+
    "\40\6\20\30\20\6\126\30\2\6\6\30\3\6\u016c\30"+
    "\2\6\21\30\1\6\32\30\5\6\113\30\3\6\13\30"+
    "\7\6\15\30\1\6\4\30\3\0\13\6\22\30\3\0"+
    "\13\6\22\30\2\0\14\6\15\30\1\6\3\30\1\6"+
    "\2\0\14\6\64\30\40\0\3\6\1\30\3\6\2\30"+
    "\1\0\2\6\12\0\41\6\4\0\1\6\12\0\6\6"+
    "\130\30\10\6\5\30\2\0\42\30\1\0\1\30\5\6"+
    "\106\30\12\6\37\30\1\6\14\0\4\6\14\0\12\6"+
    "\12\0\36\30\2\6\5\30\13\6\54\30\4\6\32\30"+
    "\6\6\12\0\46\6\27\30\5\0\4\6\65\30\12\0"+
    "\1\6\35\0\2\6\13\0\6\6\12\0\15\6\1\30"+
    "\10\6\16\0\102\6\5\0\57\30\21\0\7\30\4\6"+
    "\12\0\21\6\11\0\14\6\3\0\36\30\15\0\2\30"+
    "\12\0\54\30\16\0\14\6\44\30\24\0\10\6\12\0"+
    "\3\6\3\30\12\0\44\30\2\6\11\30\107\6\3\0"+
    "\1\6\25\0\4\30\1\0\4\30\3\0\2\30\3\0"+
    "\6\6\300\30\72\0\1\6\5\0\26\30\2\6\6\30"+
    "\2\6\46\30\2\6\6\30\2\6\10\30\1\6\1\30"+
    "\1\6\1\30\1\6\1\30\1\6\37\30\2\6\65\30"+
    "\1\6\7\30\1\6\1\30\3\6\3\30\1\6\7\30"+
    "\3\6\4\30\2\6\6\30\4\6\15\30\5\6\3\30"+
    "\1\6\7\30\16\6\5\0\30\6\2\3\5\0\20\6"+
    "\2\30\23\6\1\30\13\6\5\0\1\6\12\0\1\6"+
    "\1\30\15\6\1\30\20\6\15\30\3\6\40\30\20\6"+
    "\15\0\4\6\1\0\3\6\14\0\21\6\1\30\4\6"+
    "\1\30\2\6\12\30\1\6\1\30\3\6\5\30\6\6"+
    "\1\30\1\6\1\30\1\6\1\30\1\6\4\30\1\6"+
    "\13\30\2\6\4\30\5\6\5\30\4\6\1\30\21\6"+
    "\51\30\u0177\6\57\30\1\6\57\30\1\6\205\30\6\6"+
    "\4\30\3\0\2\30\14\6\46\30\1\6\1\30\5\6"+
    "\1\30\2\6\70\30\7\6\1\30\17\6\1\0\27\30"+
    "\11\6\7\30\1\6\7\30\1\6\7\30\1\6\7\30"+
    "\1\6\7\30\1\6\7\30\1\6\7\30\1\6\7\30"+
    "\1\6\40\0\57\6\1\30\325\6\3\30\31\6\11\30"+
    "\6\0\1\6\5\30\2\6\5\30\4\6\126\30\2\6"+
    "\2\0\2\6\3\30\1\6\132\30\1\6\4\30\5\6"+
    "\52\30\2\6\136\30\21\6\33\30\65\6\306\30\112\6"+
    "\353\30\25\6\215\30\103\6\56\30\2\6\15\30\3\6"+
    "\20\30\12\0\2\30\24\6\57\30\1\0\4\6\12\0"+
    "\1\6\37\30\2\0\120\30\2\0\45\6\11\30\2\6"+
    "\147\30\2\6\44\30\1\6\10\30\77\6\13\30\1\0"+
    "\3\30\1\0\4\30\1\0\27\30\5\0\20\6\1\30"+
    "\7\6\64\30\14\6\2\0\62\30\22\0\12\6\12\0"+
    "\6\6\22\0\6\30\3\6\1\30\1\6\1\30\2\6"+
    "\12\0\34\30\10\0\2\6\27\30\15\0\14\6\35\30"+
    "\3\6\4\0\57\30\16\0\16\6\1\30\12\0\6\6"+
    "\5\30\1\0\12\30\12\0\5\30\1\6\51\30\16\0"+
    "\11\6\3\30\1\0\10\30\2\0\2\6\12\0\6\6"+
    "\27\30\3\6\1\30\3\0\62\30\1\0\1\30\3\0"+
    "\2\30\2\0\5\30\2\0\1\30\1\0\1\30\30\6"+
    "\3\30\2\6\13\30\5\0\2\6\3\30\2\0\12\6"+
    "\6\30\2\6\6\30\2\6\6\30\11\6\7\30\1\6"+
    "\7\30\1\6\53\30\1\6\12\30\12\6\163\30\10\0"+
    "\1\6\2\0\2\6\12\0\6\6\244\30\14\6\27\30"+
    "\4\6\61\30\4\6\u0100\3\156\30\2\6\152\30\46\6"+
    "\7\30\14\6\5\30\5\6\1\30\1\0\12\30\1\6"+
    "\15\30\1\6\5\30\1\6\1\30\1\6\2\30\1\6"+
    "\2\30\1\6\154\30\41\6\153\30\22\6\100\30\2\6"+
    "\66\30\50\6\15\30\3\6\20\0\20\6\20\0\3\6"+
    "\2\30\30\6\3\30\31\6\1\30\6\6\5\30\1\6"+
    "\207\30\2\6\1\0\4\6\1\30\13\6\12\0\7\6"+
    "\32\30\4\6\1\30\1\6\32\30\13\6\131\30\3\6"+
    "\6\30\2\6\6\30\2\6\6\30\2\6\3\30\3\6"+
    "\2\30\3\6\2\30\22\6\3\0\4\6\14\30\1\6"+
    "\32\30\1\6\23\30\1\6\2\30\1\6\17\30\2\6"+
    "\16\30\42\6\173\30\105\6\65\30\210\6\1\0\202\6"+
    "\35\30\3\6\61\30\17\6\1\0\37\6\40\30\15\6"+
    "\36\30\5\6\46\30\5\0\5\6\36\30\2\6\44\30"+
    "\4\6\10\30\1\6\5\30\52\6\236\30\2\6\12\0"+
    "\6\6\44\30\4\6\44\30\4\6\50\30\10\6\64\30"+
    "\234\6\67\30\11\6\26\30\12\6\10\30\230\6\6\30"+
    "\2\6\1\30\1\6\54\30\1\6\2\30\3\6\1\30"+
    "\2\6\27\30\12\6\27\30\11\6\37\30\101\6\23\30"+
    "\1\6\2\30\12\6\26\30\12\6\32\30\106\6\70\30"+
    "\6\6\2\30\100\6\1\30\3\0\1\6\2\0\5\6"+
    "\4\0\4\30\1\6\3\30\1\6\33\30\4\6\3\0"+
    "\4\6\1\0\40\6\35\30\3\6\35\30\43\6\10\30"+
    "\1\6\34\30\2\0\31\6\66\30\12\6\26\30\12\6"+
    "\23\30\15\6\22\30\156\6\111\30\67\6\63\30\15\6"+
    "\63\30\15\6\3\0\65\30\17\0\37\6\12\0\17\6"+
    "\4\0\55\30\13\0\2\6\1\0\22\6\31\30\7\6"+
    "\12\0\6\6\3\0\44\30\16\0\1\6\12\0\20\6"+
    "\43\30\1\0\2\6\1\30\11\6\3\0\60\30\16\0"+
    "\4\30\5\6\3\0\3\6\12\0\1\30\1\6\1\30"+
    "\43\6\22\30\1\6\31\30\14\0\6\6\1\0\101\6"+
    "\7\30\1\6\1\30\1\6\4\30\1\6\17\30\1\6"+
    "\12\30\7\6\57\30\14\0\5\6\12\0\6\6\4\0"+
    "\1\6\10\30\2\6\2\30\2\6\26\30\1\6\7\30"+
    "\1\6\2\30\1\6\5\30\2\6\1\0\1\30\7\0"+
    "\2\6\2\0\2\6\3\0\2\6\1\30\6\6\1\0"+
    "\5\6\5\30\2\0\2\6\7\0\3\6\5\0\213\6"+
    "\65\30\22\0\4\30\5\6\12\0\46\6\60\30\24\0"+
    "\2\30\1\6\1\30\10\6\12\0\246\6\57\30\7\0"+
    "\2\6\11\0\27\6\4\30\2\0\42\6\60\30\21\0"+
    "\3\6\1\30\13\6\12\0\46\6\53\30\15\0\10\6"+
    "\12\0\66\6\32\30\3\6\17\0\4\6\12\0\u0166\6"+
    "\100\30\12\0\25\6\2\30\12\0\50\30\7\0\1\30"+
    "\4\0\10\6\1\0\10\6\1\30\13\0\50\30\2\6"+
    "\4\30\20\0\46\6\71\30\7\6\11\30\1\6\45\30"+
    "\10\0\1\6\10\0\1\30\17\6\12\0\30\6\36\30"+
    "\2\6\26\0\1\6\16\0\111\6\7\30\1\6\2\30"+
    "\1\6\46\30\6\0\3\6\1\0\1\6\2\0\1\6"+
    "\7\0\1\30\1\0\10\6\12\0\246\6\232\30\146\6"+
    "\157\30\21\6\304\30\274\6\57\30\321\6\107\30\271\6"+
    "\71\30\7\6\37\30\1\6\12\0\146\6\36\30\2\6"+
    "\5\0\13\6\60\30\7\0\11\6\4\30\14\6\12\0"+
    "\11\6\25\30\5\6\23\30\160\6\105\30\13\6\1\30"+
    "\56\0\20\6\4\0\15\30\100\6\2\30\36\6\355\30"+
    "\23\6\363\30\15\6\37\30\121\6\u018c\30\4\6\153\30"+
    "\5\6\15\30\3\6\11\30\7\6\12\30\3\6\2\0"+
    "\1\6\4\0\301\6\5\0\3\6\26\0\2\6\7\0"+
    "\36\6\4\0\224\6\3\0\273\6\125\30\1\6\107\30"+
    "\1\6\2\30\2\6\1\30\2\6\2\30\2\6\4\30"+
    "\1\6\14\30\1\6\1\30\1\6\7\30\1\6\101\30"+
    "\1\6\4\30\2\6\10\30\1\6\7\30\1\6\34\30"+
    "\1\6\4\30\1\6\5\30\1\6\1\30\3\6\7\30"+
    "\1\6\u0154\30\2\6\31\30\1\6\31\30\1\6\37\30"+
    "\1\6\31\30\1\6\37\30\1\6\31\30\1\6\37\30"+
    "\1\6\31\30\1\6\37\30\1\6\31\30\1\6\10\30"+
    "\2\6\151\0\4\6\62\0\10\6\1\0\16\6\1\0"+
    "\26\6\5\0\1\6\17\0\120\6\7\0\1\6\21\0"+
    "\2\6\7\0\1\6\2\0\1\6\5\0\325\6\305\30"+
    "\13\6\7\0\51\6\104\30\7\0\5\6\12\0\246\6"+
    "\4\30\1\6\33\30\1\6\2\30\1\6\1\30\2\6"+
    "\1\30\1\6\12\30\1\6\4\30\1\6\1\30\1\6"+
    "\1\30\6\6\1\30\4\6\1\30\1\6\1\30\1\6"+
    "\1\30\1\6\3\30\1\6\2\30\1\6\1\30\2\6"+
    "\1\30\1\6\1\30\1\6\1\30\1\6\1\30\1\6"+
    "\1\30\1\6\2\30\1\6\1\30\2\6\4\30\1\6"+
    "\7\30\1\6\4\30\1\6\4\30\1\6\1\30\1\6"+
    "\12\30\1\6\21\30\5\6\3\30\1\6\5\30\1\6"+
    "\21\30\104\6\327\30\51\6\65\30\13\6\336\30\2\6"+
    "\u0182\30\16\6\u0131\30\37\6\36\30\343\6\1\0\36\6"+
    "\140\0\200\6\360\0\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\1\1\23\15\5\1\24"+
    "\1\25\1\26\1\27\1\30\2\1\1\31\1\0\1\32"+
    "\1\33\1\34\1\35\3\5\1\36\2\5\1\37\3\5"+
    "\1\40\4\5\1\41\1\42\1\43\1\44\2\0\1\31"+
    "\1\0\1\45\1\5\1\46\1\5\1\47\1\50\1\51"+
    "\1\52\1\53\2\5\1\54\1\5\2\0\1\2\1\55"+
    "\1\56\1\57\2\5\1\60\1\5\1\0\1\2\2\5"+
    "\1\61\1\5\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\304\0\365\0\304"+
    "\0\304\0\u0126\0\u0157\0\304\0\304\0\304\0\304\0\304"+
    "\0\304\0\304\0\u0188\0\304\0\304\0\u01b9\0\304\0\u01ea"+
    "\0\304\0\u021b\0\304\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310"+
    "\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498"+
    "\0\304\0\304\0\u04c9\0\304\0\u04fa\0\u052b\0\u055c\0\u058d"+
    "\0\u05be\0\304\0\304\0\304\0\u05ef\0\u0620\0\u0651\0\u0682"+
    "\0\u0126\0\u06b3\0\u06e4\0\u0126\0\u0715\0\u0746\0\u0777\0\u0126"+
    "\0\u07a8\0\u07d9\0\u080a\0\u083b\0\304\0\304\0\304\0\304"+
    "\0\u086c\0\u089d\0\304\0\u08ce\0\u0126\0\u08ff\0\u0126\0\u0930"+
    "\0\u0126\0\u0126\0\u0126\0\u0961\0\u0126\0\u0992\0\u09c3\0\u0126"+
    "\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\304\0\u0126\0\u0126\0\u0ab8"+
    "\0\u0ae9\0\u0126\0\u0b1a\0\u0b4b\0\u0a25\0\u0b7c\0\u0bad\0\u0126"+
    "\0\u0bde\0\u0126\0\u0126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\5\1\6\1\7\1\5\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\12"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\2\12\1\41\1\12\1\42\1\43\1\44\1\45\1\12"+
    "\1\46\1\12\1\47\1\50\1\51\1\52\1\5\2\53"+
    "\1\5\2\53\1\5\1\53\1\54\22\53\1\55\26\53"+
    "\32\5\1\56\60\5\1\57\26\5\63\0\1\6\56\0"+
    "\1\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\22\12\2\0\1\12\2\60\1\0\7\60\1\0\17\60"+
    "\1\61\26\60\21\0\2\23\56\0\1\62\5\0\1\63"+
    "\60\0\1\64\43\0\1\65\47\0\1\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\12\12\1\66\7\12"+
    "\2\0\2\12\10\0\1\12\7\0\2\12\5\0\1\12"+
    "\3\0\6\12\1\67\13\12\2\0\2\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\7\12\1\70\3\12"+
    "\1\71\6\12\2\0\2\12\10\0\1\12\7\0\2\12"+
    "\5\0\1\12\3\0\10\12\1\72\11\12\2\0\2\12"+
    "\10\0\1\12\7\0\2\12\5\0\1\12\3\0\17\12"+
    "\1\73\2\12\2\0\2\12\10\0\1\12\7\0\2\12"+
    "\5\0\1\12\3\0\4\12\1\74\5\12\1\75\7\12"+
    "\2\0\2\12\10\0\1\12\7\0\2\12\5\0\1\12"+
    "\3\0\13\12\1\76\6\12\2\0\2\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\13\12\1\77\6\12"+
    "\2\0\2\12\10\0\1\12\7\0\2\12\5\0\1\12"+
    "\3\0\14\12\1\100\5\12\2\0\2\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\3\12\1\101\16\12"+
    "\2\0\2\12\10\0\1\12\7\0\2\12\5\0\1\12"+
    "\3\0\6\12\1\102\13\12\2\0\2\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\1\103\21\12\2\0"+
    "\2\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\6\12\1\104\13\12\2\0\1\12\2\53\1\0\2\53"+
    "\1\0\1\53\1\0\22\53\1\0\26\53\7\0\1\105"+
    "\36\0\1\106\1\0\1\107\1\0\1\110\17\0\1\111"+
    "\60\0\1\112\61\0\1\113\46\0\2\60\4\0\52\60"+
    "\33\0\1\114\26\0\1\12\10\0\1\12\7\0\2\12"+
    "\5\0\1\12\3\0\2\12\1\115\17\12\2\0\2\12"+
    "\10\0\1\12\7\0\2\12\5\0\1\12\3\0\1\116"+
    "\21\12\2\0\2\12\10\0\1\12\7\0\2\12\5\0"+
    "\1\12\3\0\20\12\1\117\1\12\2\0\2\12\10\0"+
    "\1\12\7\0\2\12\5\0\1\12\3\0\15\12\1\120"+
    "\4\12\2\0\2\12\10\0\1\12\7\0\2\12\5\0"+
    "\1\12\3\0\12\12\1\121\7\12\2\0\2\12\10\0"+
    "\1\12\7\0\2\12\5\0\1\12\3\0\16\12\1\122"+
    "\3\12\2\0\2\12\10\0\1\12\7\0\2\12\5\0"+
    "\1\12\3\0\2\12\1\123\17\12\2\0\2\12\10\0"+
    "\1\12\7\0\2\12\5\0\1\12\3\0\16\12\1\124"+
    "\3\12\2\0\2\12\10\0\1\12\7\0\2\12\5\0"+
    "\1\12\3\0\4\12\1\125\11\12\1\126\3\12\2\0"+
    "\2\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\3\12\1\127\16\12\2\0\2\12\10\0\1\12\7\0"+
    "\2\12\5\0\1\12\3\0\14\12\1\130\5\12\2\0"+
    "\2\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\7\12\1\131\12\12\2\0\1\12\11\132\1\0\20\132"+
    "\1\133\26\132\11\134\1\0\47\134\11\0\1\135\47\0"+
    "\1\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\14\12\1\136\5\12\2\0\2\12\10\0\1\12\7\0"+
    "\2\12\5\0\1\12\3\0\3\12\1\137\16\12\2\0"+
    "\2\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\6\12\1\140\13\12\2\0\2\12\10\0\1\12\7\0"+
    "\2\12\5\0\1\12\3\0\17\12\1\141\2\12\2\0"+
    "\2\12\10\0\1\12\7\0\2\12\5\0\1\12\3\0"+
    "\12\12\1\142\7\12\2\0\2\12\10\0\1\12\7\0"+
    "\2\12\5\0\1\12\3\0\10\12\1\143\11\12\2\0"+
    "\1\12\32\132\1\144\37\132\1\145\20\132\1\144\26\132"+
    "\2\0\1\6\2\0\1\7\53\0\1\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\7\12\1\146\12\12"+
    "\2\0\2\12\10\0\1\12\7\0\2\12\5\0\1\12"+
    "\3\0\14\12\1\147\5\12\2\0\2\12\10\0\1\12"+
    "\7\0\2\12\5\0\1\12\3\0\3\12\1\150\16\12"+
    "\2\0\1\12\11\132\1\6\20\132\1\144\26\132\1\12"+
    "\10\0\1\12\7\0\2\12\5\0\1\12\3\0\12\12"+
    "\1\151\7\12\2\0\2\12\10\0\1\12\7\0\2\12"+
    "\5\0\1\12\3\0\12\12\1\152\7\12\2\0\2\12"+
    "\10\0\1\12\7\0\2\12\5\0\1\12\3\0\5\12"+
    "\1\153\14\12\2\0\1\12";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3087];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\1\1\2\11\2\1\7\11\1\1\2\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\15\1\2\11"+
    "\1\1\1\11\4\1\1\0\3\11\20\1\4\11\2\0"+
    "\1\11\1\0\15\1\2\0\1\1\1\11\6\1\1\0"+
    "\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private StringBuffer sb = new StringBuffer();

    private Symbol createSymbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+1);
    }

    private Symbol createSymbol(int type, Object value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return createSymbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException((yyline+1) + ":" + (yycolumn+1) + ": illegal character <"+ yytext()+">");
            }
            // fall through
          case 52: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 53: break;
          case 3:
            { sb.setLength(0); yybegin(STRING);
            }
            // fall through
          case 54: break;
          case 4:
            { return createSymbol(sym.NEQ);
            }
            // fall through
          case 55: break;
          case 5:
            { return createSymbol(sym.IDENTIFIER, yytext());
            }
            // fall through
          case 56: break;
          case 6:
            { return createSymbol(sym.LPAREN);
            }
            // fall through
          case 57: break;
          case 7:
            { return createSymbol(sym.RPAREN);
            }
            // fall through
          case 58: break;
          case 8:
            { return createSymbol(sym.TIMES);
            }
            // fall through
          case 59: break;
          case 9:
            { return createSymbol(sym.PLUS);
            }
            // fall through
          case 60: break;
          case 10:
            { return createSymbol(sym.COMMA);
            }
            // fall through
          case 61: break;
          case 11:
            { return createSymbol(sym.MINUS);
            }
            // fall through
          case 62: break;
          case 12:
            { return createSymbol(sym.INTEGER_LITERAL, Integer.valueOf(yytext()));
            }
            // fall through
          case 63: break;
          case 13:
            { return createSymbol(sym.COLON);
            }
            // fall through
          case 64: break;
          case 14:
            { return createSymbol(sym.SEMICOLON);
            }
            // fall through
          case 65: break;
          case 15:
            { return createSymbol(sym.LTHAN);
            }
            // fall through
          case 66: break;
          case 16:
            { return createSymbol(sym.EQ);
            }
            // fall through
          case 67: break;
          case 17:
            { return createSymbol(sym.GTHAN);
            }
            // fall through
          case 68: break;
          case 18:
            { return createSymbol(sym.LBRACKET);
            }
            // fall through
          case 69: break;
          case 19:
            { return createSymbol(sym.RBRACKET);
            }
            // fall through
          case 70: break;
          case 20:
            { return createSymbol(sym.LCURLY);
            }
            // fall through
          case 71: break;
          case 21:
            { return createSymbol(sym.RCURLY);
            }
            // fall through
          case 72: break;
          case 22:
            { sb.append(yytext());
            }
            // fall through
          case 73: break;
          case 23:
            { yybegin(YYINITIAL);
                                     return createSymbol(sym.STRING_LITERAL, sb.toString());
            }
            // fall through
          case 74: break;
          case 24:
            { sb.append('\\');
            }
            // fall through
          case 75: break;
          case 25:
            { return createSymbol(sym.CHAR_LITERAL, yytext());
            }
            // fall through
          case 76: break;
          case 26:
            { return createSymbol(sym.SPACER);
            }
            // fall through
          case 77: break;
          case 27:
            { return createSymbol(sym.LEQ);
            }
            // fall through
          case 78: break;
          case 28:
            { return createSymbol(sym.GEQ);
            }
            // fall through
          case 79: break;
          case 29:
            { yybegin(SINGLE_COMMENT);
            }
            // fall through
          case 80: break;
          case 30:
            { return createSymbol(sym.DO);
            }
            // fall through
          case 81: break;
          case 31:
            { return createSymbol(sym.IF);
            }
            // fall through
          case 82: break;
          case 32:
            { return createSymbol(sym.OR);
            }
            // fall through
          case 83: break;
          case 33:
            { sb.append('\"');
            }
            // fall through
          case 84: break;
          case 34:
            { sb.append('\n');
            }
            // fall through
          case 85: break;
          case 35:
            { sb.append('\r');
            }
            // fall through
          case 86: break;
          case 36:
            { sb.append('\t');
            }
            // fall through
          case 87: break;
          case 37:
            { return createSymbol(sym.AND);
            }
            // fall through
          case 88: break;
          case 38:
            { return createSymbol(sym.DIV);
            }
            // fall through
          case 89: break;
          case 39:
            { return createSymbol(sym.FUN);
            }
            // fall through
          case 90: break;
          case 40:
            { return createSymbol(sym.INT);
            }
            // fall through
          case 91: break;
          case 41:
            { return createSymbol(sym.MOD);
            }
            // fall through
          case 92: break;
          case 42:
            { return createSymbol(sym.NOT);
            }
            // fall through
          case 93: break;
          case 43:
            { return createSymbol(sym.REF);
            }
            // fall through
          case 94: break;
          case 44:
            { return createSymbol(sym.VAR);
            }
            // fall through
          case 95: break;
          case 45:
            { yybegin(COMMENT);
            }
            // fall through
          case 96: break;
          case 46:
            { return createSymbol(sym.CHAR);
            }
            // fall through
          case 97: break;
          case 47:
            { return createSymbol(sym.ELSE);
            }
            // fall through
          case 98: break;
          case 48:
            { return createSymbol(sym.THEN);
            }
            // fall through
          case 99: break;
          case 49:
            { return createSymbol(sym.WHILE);
            }
            // fall through
          case 100: break;
          case 50:
            { return createSymbol(sym.RETURN);
            }
            // fall through
          case 101: break;
          case 51:
            { return createSymbol(sym.NOTHING);
            }
            // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
