
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 27 21:59:04 EEST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 40;
  public static final int LBRACKET = 24;
  public static final int CHAR = 5;
  public static final int CHAR_LITERAL = 41;
  public static final int LPAREN = 18;
  public static final int INT = 6;
  public static final int MINUS = 38;
  public static final int REF = 14;
  public static final int RPAREN = 19;
  public static final int NOT = 4;
  public static final int SEMICOLON = 20;
  public static final int AND = 2;
  public static final int LTHAN = 31;
  public static final int FUN = 9;
  public static final int OR = 3;
  public static final int COMMA = 26;
  public static final int DIV = 35;
  public static final int GEQ = 30;
  public static final int PLUS = 37;
  public static final int IF = 10;
  public static final int SPACER = 33;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 25;
  public static final int error = 1;
  public static final int LCURLY = 22;
  public static final int MOD = 36;
  public static final int NEQ = 28;
  public static final int EQ = 27;
  public static final int RCURLY = 23;
  public static final int TIMES = 34;
  public static final int GTHAN = 32;
  public static final int COLON = 21;
  public static final int ELSE = 11;
  public static final int WHILE = 8;
  public static final int THEN = 12;
  public static final int LEQ = 29;
  public static final int NOTHING = 13;
  public static final int VAR = 16;
  public static final int DO = 7;
  public static final int INTEGER_LITERAL = 39;
  public static final int IDENTIFIER = 17;
}

