
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 01 20:15:30 EEST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 41;
  public static final int LBRACKET = 25;
  public static final int CHAR = 6;
  public static final int CHAR_LITERAL = 42;
  public static final int LPAREN = 19;
  public static final int INT = 7;
  public static final int MINUS = 39;
  public static final int REF = 15;
  public static final int RPAREN = 20;
  public static final int NOT = 4;
  public static final int SEMICOLON = 21;
  public static final int AND = 2;
  public static final int LTHAN = 32;
  public static final int FUN = 10;
  public static final int OR = 3;
  public static final int COMMA = 27;
  public static final int DIV = 36;
  public static final int GEQ = 31;
  public static final int PLUS = 38;
  public static final int IF = 11;
  public static final int SPACER = 34;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int RBRACKET = 26;
  public static final int error = 1;
  public static final int LCURLY = 23;
  public static final int MOD = 37;
  public static final int NEQ = 29;
  public static final int EQ = 28;
  public static final int RCURLY = 24;
  public static final int TIMES = 35;
  public static final int GTHAN = 33;
  public static final int COLON = 22;
  public static final int PUTS = 5;
  public static final int ELSE = 12;
  public static final int WHILE = 9;
  public static final int THEN = 13;
  public static final int LEQ = 30;
  public static final int NOTHING = 14;
  public static final int VAR = 17;
  public static final int DO = 8;
  public static final int INTEGER_LITERAL = 40;
  public static final int IDENTIFIER = 18;
}

